name: on_boarding_ui
description: A Flutter package for On Boarding Screen.
version: 0.0.4
homepage: https://github.com/ishaquehassan/FlutterOnBoardingUIPackage.git

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  # To add assets to your package, add an assets section, like this:

